import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    appName: 'EcoGuard AI',
    tagline: 'Smart Industrial Pollution Monitoring',
    dashboard: 'Dashboard',
    liveMonitoring: 'Live Monitoring',
    airQuality: 'Air Quality',
    waterQuality: 'Water Quality',
    industries: 'Industries',
    sensors: 'Sensors',
    violations: 'Violations',
    alerts: 'Alerts',
    healthRisk: 'Health Risk',
    pollutionMap: 'Pollution Map',
    analytics: 'Analytics',
    aiReports: 'AI Reports',
    agentMonitoring: 'Agent Monitoring',
    settings: 'Settings',
    login: 'Login',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    totalIndustries: 'Total Industries',
    activeSensors: 'Active Sensors',
    activeViolations: 'Active Violations',
    criticalAlerts: 'Critical Alerts',
    highRiskZones: 'High Risk Zones',
    complianceScore: 'Compliance Score',
    currentAQI: 'Current AQI',
    recentIncidents: 'Recent Incidents',
    loading: 'Loading...',
    noData: 'No data available',
    acknowledge: 'Acknowledge',
    resolve: 'Resolve',
    escalate: 'Escalate',
    generateReport: 'Generate AI Report',
    normal: 'Normal',
    warning: 'Warning',
    high: 'High',
    critical: 'Critical',
    good: 'Good',
    moderate: 'Moderate',
    unhealthy: 'Unhealthy',
    hazardous: 'Hazardous',
    search: 'Search...',
    filter: 'Filter',
    exportCSV: 'Export CSV',
    zone: 'Zone',
    industryType: 'Industry Type',
    status: 'Status',
    severity: 'Severity',
    detectedAt: 'Detected At',
    actions: 'Actions',
    viewDetails: 'View Details',
  },
  hi: {
    appName: 'इकोगार्ड AI',
    tagline: 'स्मार्ट औद्योगिक प्रदूषण निगरानी',
    dashboard: 'डैशबोर्ड',
    liveMonitoring: 'लाइव मॉनिटरिंग',
    airQuality: 'वायु गुणवत्ता',
    waterQuality: 'जल गुणवत्ता',
    industries: 'उद्योग',
    sensors: 'सेंसर',
    violations: 'उल्लंघन',
    alerts: 'अलर्ट',
    healthRisk: 'स्वास्थ्य जोखिम',
    pollutionMap: 'प्रदूषण मानचित्र',
    analytics: 'विश्लेषण',
    aiReports: 'AI रिपोर्ट',
    agentMonitoring: 'एजेंट निगरानी',
    settings: 'सेटिंग्स',
    login: 'लॉग इन',
    logout: 'लॉग आउट',
    email: 'ईमेल',
    password: 'पासवर्ड',
    totalIndustries: 'कुल उद्योग',
    activeSensors: 'सक्रिय सेंसर',
    activeViolations: 'सक्रिय उल्लंघन',
    criticalAlerts: 'गंभीर अलर्ट',
    highRiskZones: 'उच्च जोखिम क्षेत्र',
    complianceScore: 'अनुपालन स्कोर',
    currentAQI: 'वर्तमान AQI',
    recentIncidents: 'हालिया घटनाएं',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा उपलब्ध नहीं',
    acknowledge: 'स्वीकार करें',
    resolve: 'हल करें',
    escalate: 'एस्केलेट करें',
    generateReport: 'AI रिपोर्ट बनाएं',
    normal: 'सामान्य',
    warning: 'चेतावनी',
    high: 'उच्च',
    critical: 'गंभीर',
    good: 'अच्छा',
    moderate: 'मध्यम',
    unhealthy: 'अस्वस्थ',
    hazardous: 'खतरनाक',
    search: 'खोजें...',
    filter: 'फ़िल्टर',
    exportCSV: 'CSV निर्यात',
    zone: 'क्षेत्र',
    industryType: 'उद्योग प्रकार',
    status: 'स्थिति',
    severity: 'गंभीरता',
    detectedAt: 'पता चला',
    actions: 'कार्रवाई',
    viewDetails: 'विवरण देखें',
  },
  gu: {
    appName: 'ઇકોગાર્ડ AI',
    tagline: 'સ્માર્ટ ઔદ્યોગિક પ્રદૂષણ દેખરેખ',
    dashboard: 'ડેશબોર્ડ',
    liveMonitoring: 'લાઇવ મૉનિટરિંગ',
    airQuality: 'હવાની ગુણવત્તા',
    waterQuality: 'પાણીની ગુણવત્તા',
    industries: 'ઉદ્યોગો',
    sensors: 'સેન્સર',
    violations: 'ઉલ્લંઘનો',
    alerts: 'અલર્ટ',
    healthRisk: 'સ્વાસ્થ્ય જોખમ',
    pollutionMap: 'પ્રદૂષણ નકશો',
    analytics: 'વિશ્લેષણ',
    aiReports: 'AI અહેવાલ',
    agentMonitoring: 'એજન્ટ દેખરેખ',
    settings: 'સેટિંગ્સ',
    login: 'લૉગ ઇન',
    logout: 'લૉગ આઉટ',
    email: 'ઇમેઇલ',
    password: 'પાસવર્ડ',
    totalIndustries: 'કુલ ઉદ્યોગો',
    activeSensors: 'સક્રિય સેન્સર',
    activeViolations: 'સક્રિય ઉલ્લંઘન',
    criticalAlerts: 'ગંભીર અલર્ટ',
    highRiskZones: 'ઉચ્ચ જોખમ ઝોન',
    complianceScore: 'અનુપાલન સ્કોર',
    currentAQI: 'વર્તમાન AQI',
    recentIncidents: 'તાજેતરની ઘટનાઓ',
    loading: 'લોડ થઈ રહ્યું છે...',
    noData: 'કોઈ ડેટા ઉપલબ્ધ નથી',
    acknowledge: 'સ્વીકારો',
    resolve: 'ઉકેલો',
    escalate: 'એસ્કેલેટ કરો',
    generateReport: 'AI અહેવાલ બનાવો',
    normal: 'સામાન્ય',
    warning: 'ચેતવણી',
    high: 'ઉચ્ચ',
    critical: 'ગંભીર',
    good: 'સારો',
    moderate: 'મધ્યમ',
    unhealthy: 'અસ્વસ્થ',
    hazardous: 'જોખમી',
    search: 'શોધો...',
    filter: 'ફિલ્ટર',
    exportCSV: 'CSV નિકાસ',
    zone: 'ઝોન',
    industryType: 'ઉદ્યોગ પ્રકાર',
    status: 'સ્થિતિ',
    severity: 'ગંભીરતા',
    detectedAt: 'શોધ્યું',
    actions: 'ક્રિયાઓ',
    viewDetails: 'વિગતો જુઓ',
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem('eco_lang') || 'en');

  const changeLang = (l) => {
    setLang(l);
    localStorage.setItem('eco_lang', l);
  };

  const t = (key) => (translations[lang] || translations.en)[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
